# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "78a5f6fc8bc3472a08d62afda49c9e6b"
name = "gamifyme"
handle = "gamifyme"
application_url = "https://cant-plug-contribute-receipt.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cant-plug-contribute-receipt.trycloudflare.com/auth/callback",
  "https://cant-plug-contribute-receipt.trycloudflare.com/auth/shopify/callback",
  "https://cant-plug-contribute-receipt.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
